#version 460

#include "shared.inc.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 1, scalar) readonly restrict buffer CullInfos {
    uint count;
    ModelCullInfo model[];
} cullInfos[6];

layout(set = 0, binding = 3, scalar) buffer ModelsDrawInfo {
    uint drawCount;
    VkDrawIndexedIndirectCommand drawInfos[];
} modelsDrawInfo[6];
layout(set = 0, binding = 3, scalar) buffer VkDrawIndirectCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
} actorWallsDrawInfo[6];

void main() {
    modelsDrawInfo[0].drawCount = 0;
    modelsDrawInfo[1].drawCount = 0;

    actorWallsDrawInfo[2].vertexCount = 12;
    actorWallsDrawInfo[2].instanceCount = 0;
    actorWallsDrawInfo[2].firstVertex = 0;
    actorWallsDrawInfo[2].firstInstance = 0;

    actorWallsDrawInfo[3].vertexCount = 12;
    actorWallsDrawInfo[3].instanceCount = 0;
    actorWallsDrawInfo[3].firstVertex = 0;
    actorWallsDrawInfo[3].firstInstance = 0;
}
