#version 460

#include "include/types.inc.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant, scalar) uniform PushConstants {
	uint actorModelsDrawInfoCount;
} pushConstants;

layout(set = 0, binding = 0, scalar) buffer CullingData {
    FrustumCullingData frustums[];
} cullingData;

#define SetSafe(ref, field, value) if (uvec2(ref) != uvec2(0)) (ref).field = (value);

void main() {
    const uint index = gl_GlobalInvocationID.x;
    const uint frustumIndex = gl_GlobalInvocationID.y;
    // TODO: This branch will cause threads to require masking the majority of the time!
    if (index == 0) {
        SetSafe(cullingData.frustums[frustumIndex].shadedOpaqueMapModelsOutputDrawInfo, count, 0);
        SetSafe(cullingData.frustums[frustumIndex].unshadedOpaqueMapModelsOutputDrawInfo, count, 0);
        SetSafe(cullingData.frustums[frustumIndex].shadedMapModelsOutputDrawInfo, count, 0);
        SetSafe(cullingData.frustums[frustumIndex].unshadedMapModelsOutputDrawInfo, count, 0);

        // TODO: Initialize actor wall draw infos so that only the instance count needs to be reset
        SetSafe(cullingData.frustums[frustumIndex].shadedActorWallsDrawInfo, vertexCount, 12);
        SetSafe(cullingData.frustums[frustumIndex].shadedActorWallsDrawInfo, instanceCount, 0);
        SetSafe(cullingData.frustums[frustumIndex].shadedActorWallsDrawInfo, firstVertex, 0);
        SetSafe(cullingData.frustums[frustumIndex].shadedActorWallsDrawInfo, firstInstance, 0);

        SetSafe(cullingData.frustums[frustumIndex].unshadedActorWallsDrawInfo, vertexCount, 12);
        SetSafe(cullingData.frustums[frustumIndex].unshadedActorWallsDrawInfo, instanceCount, 0);
        SetSafe(cullingData.frustums[frustumIndex].unshadedActorWallsDrawInfo, firstVertex, 0);
        SetSafe(cullingData.frustums[frustumIndex].unshadedActorWallsDrawInfo, firstInstance, 0);
    }
    if (index >= pushConstants.actorModelsDrawInfoCount) {
        return;
    }
    SetSafe(cullingData.frustums[frustumIndex].shadedActorModelsDrawInfo, drawInfos[index].instanceCount, 0);
    SetSafe(cullingData.frustums[frustumIndex].unshadedActorModelsDrawInfo, drawInfos[index].instanceCount, 0);
}
