#version 460

#include "shared.inc.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    uint frustumIndex;
} pushConstants;

layout(set = 1, binding = 0, scalar) readonly restrict buffer Frustums {
    Frustum frustums[];
} frustums;

layout(set = 1, binding = 1, scalar) readonly restrict buffer CullInfos {
    uint count;
    ModelCullInfo model[];
} cullInfos[8];

layout(set = 1, binding = 2, scalar) buffer UnculledDrawInfo {
    VkDrawIndexedIndirectCommand drawInfos[];
} unculledDrawInfo[8];
layout(set = 1, binding = 2, scalar) buffer InstanceIndices {
    uint instanceIndex[];
} instanceIndices[8];

layout(set = 1, binding = 3, scalar) buffer ModelsDrawInfo {
    uint drawCount;
    VkDrawIndexedIndirectCommand drawInfos[];
} modelsDrawInfo[8];
layout(set = 1, binding = 3, scalar) buffer VkDrawIndirectCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
} actorWallsDrawInfo[8];

bool IsVisible(const ModelCullInfo cullInfo) {
    if (pushConstants.frustumIndex == -1) {
        const vec3 center = (camera.viewMatrix * vec4(cullInfo.position, 1)).xyz;
        return center.z + cullInfo.radius > camera.nearPlane && center.z - cullInfo.radius < camera.farPlane &&
               center.z * camera.frustumPlanes[1] - abs(center.x) * camera.frustumPlanes[0] > -cullInfo.radius &&
               center.z * camera.frustumPlanes[3] - abs(center.y) * camera.frustumPlanes[2] > -cullInfo.radius;
    }

    // if (cullInfo.castsShadows == 0) {
    //     return false;
    // }
    const Frustum frustum = frustums.frustums[pushConstants.frustumIndex];
    const vec3 center = (frustum.viewMatrix * vec4(cullInfo.position, 1)).xyz;
    return center.z + cullInfo.radius > frustum.nearPlane && center.z - cullInfo.radius < frustum.farPlane &&
           center.z * frustum.frustumPlanes[1] - abs(center.x) * frustum.frustumPlanes[0] > -cullInfo.radius &&
           center.z * frustum.frustumPlanes[3] - abs(center.y) * frustum.frustumPlanes[2] > -cullInfo.radius;
}

void CullMapModel(const uint bufferIndex, const uint index) {
    if (IsVisible(cullInfos[bufferIndex].model[index])) {
        const uint drawIndex = atomicAdd(modelsDrawInfo[bufferIndex].drawCount, 1);
        modelsDrawInfo[bufferIndex].drawInfos[drawIndex] = unculledDrawInfo[bufferIndex].drawInfos[index];
    }
}

void CullWallActor(const uint bufferIndex, const uint index) {
    if (IsVisible(cullInfos[bufferIndex].model[index])) {
        const uint drawIndex = atomicAdd(actorWallsDrawInfo[bufferIndex].instanceCount, 1);
        if (bufferIndex == 4) {
            instanceIndices[4].instanceIndex[drawIndex] = index;
        } else {
            instanceIndices[5].instanceIndex[drawIndex] = index + cullInfos[4].count;
        }
    }
}

void main() {
    const uint bufferIndex = gl_GlobalInvocationID.y;
    const uint index = gl_GlobalInvocationID.x;
    if (index >= cullInfos[bufferIndex].count) {
        return;
    }

    if (bufferIndex < 4) {
        CullMapModel(bufferIndex, index);
    } else if (bufferIndex < 6) {
        CullWallActor(bufferIndex, index);
    } else {
        // TODO: Actor models
    }
}